import sys
from typing import Iterable, Optional, NoReturn

from compiler.types import VoidType, BoolType, IntType, ObjectType, FunctionType, Type
from compiler.symbols import LocalSymbol, ParameterSymbol, FieldSymbol, Class
from lang_ast import (
    ClassDecl, ClassField, FuncDecl, ReturnStmt, _Statement, IntExpr,
    _Expression, BoolExpr, StringExpr, BinaryExpr, BinaryOperation,
    SymbolExpr, CallExpr, MemberExpr, ExprStmt, IfStmt, VarStmt,
    AllocExpr, AssignStmt, _TopLevelDecl, _SymbolRefExpr
)


def fatal_error(msg: str) -> NoReturn:
    sys.exit(f"internal error: {msg}\nThis is a bug in the compiler, semantic analysis should've caught this!")


class LLVMIRGenerator:
    def __init__(self, ast: list[_TopLevelDecl]):
        self.ast = ast
        self._lines: list[str] = []
        self._strings: list[str] = []
        self._temp_idx: int = 0
        self._if_idx: int = 0
        self._current_class: Optional[ClassDecl] = None

        self._declarations = [
            "declare ptr @zre_alloc(ptr)",
            "declare i1 @zre_field_get_bool(ptr, ptr)",
            "declare i64 @zre_field_get_int(ptr, ptr)",
            "declare ptr @zre_field_get_obj(ptr, ptr)",
            "declare void @zre_field_set_bool(ptr, ptr, i1)",
            "declare void @zre_field_set_int(ptr, ptr, i64)",
            "declare void @zre_field_set_obj(ptr, ptr, ptr)",
            "declare ptr @zre_method_super(ptr, ptr)",
            "declare ptr @zre_method_virtual(ptr, ptr)",
            "declare ptr @zre_string_literal(ptr)",
            # TODO: Better way to handle built-in types?
            "declare void @_zr_print(ptr)",
            "@Object = external constant ptr",
            "@String = external constant ptr",
            "@Array = external constant ptr",
            "@File = external constant ptr",
            "@User = external constant ptr",
        ]

    def generate(self) -> str:
        self._emit("; Generated by zrlang")

        for decl in self.ast:
            if isinstance(decl, FuncDecl):
                self._emit_function(decl)
            elif isinstance(decl, ClassDecl):
                self._emit_class(decl)

        self._emit("\n; String data")
        for idx, string in enumerate(self._strings):
            self._emit(f"@.str.{idx} = private unnamed_addr constant [{len(string) + 1} x i8] c\"{string}\\00\"")

        self._emit("\n; External declarations")
        for decl in self._declarations:
            self._emit(decl)
        self._emit("")

        return "\n".join(self._lines)

    def _str_sym(self, string: str) -> str:
        self._strings.append(string)
        return f"@.str.{len(self._strings) - 1}"

    def _emit(self, line: str | list[str]):
        self._lines.append(line)

    def _emit_function(self, func: FuncDecl):
        self._emit(f"; ==== \"{func.name}\" Function ====")
        name = "main" if func.name == "main" else f"_zr_{func.name}"
        self._emit_function_impl(func, name, linkage="")
        self._emit("")

    def _emit_class(self, cls: ClassDecl):
        self._current_class = cls
        self._emit(f"; ==== \"{cls.name}\" Class Definition ====")

        fields = list(filter(lambda x: isinstance(x, ClassField), cls.members))
        if fields:
            self._emit(f"@{cls.name}.fields = constant [{len(fields)} x {{ ptr, i64 }}] [")
            self._emit(",\n".join(f"\t{{ ptr, i64 }} {{ ptr {self._str_sym(field.name)}, i64 0 }}"
                                  for field in fields))
            self._emit("]")

        # TODO: Replace ptrtoint with actual LLVM struct types
        methods = list(filter(lambda x: isinstance(x, FuncDecl), cls.members))
        if methods:
            self._emit(f"@{cls.name}.instanceMethods = constant [{len(methods)} x {{ ptr, ptr }}] [")
            self._emit(",\n".join(f"\t{{ ptr, ptr }} {{ ptr {self._str_sym(method.name)}, ptr @{cls.name}.{method.name} }}"
                                  for method in methods))
            self._emit("]")

        # -- Class table ---
        self._emit(f"@{cls.name} = constant [8 x i64] [")
        self._emit(f"\ti64 ptrtoint(ptr {self._str_sym(cls.name)} to i64),")
        self._emit(f"\ti64 ptrtoint(ptr @{cls.super or "Object"} to i64),")

        if fields:
            self._emit(f"\ti64 {len(fields)}, i64 ptrtoint (ptr @{cls.name}.fields to i64),")
        else:
            self._emit("\ti64 0, i64 0,")

        self._emit("\ti64 0, i64 0,")

        if methods:
            self._emit(f"\ti64 {len(methods)}, i64 ptrtoint (ptr @{cls.name}.instanceMethods to i64)")
        else:
            self._emit("\ti64 0, i64 0")
        self._emit("]")
        # ---

        if methods:
            self._emit(f"\n; ==== \"{cls.name}\" Methods ====")
            for method in methods:
                self._emit_method(cls, method)
        self._current_class = None

    def _emit_method(self, cls: ClassDecl, method: FuncDecl):
        self._emit_function_impl(method, f"{cls.name}.{method.name}", linkage="internal", add_self=True)

    def _emit_function_impl(self, func: FuncDecl, name: str, linkage: str = "", add_self: bool = False):
        params = [f"{self._type_to_ir(param.type)} %{param.name}" for param in func.params]
        if add_self:
            params.insert(0, "ptr %self")

        self._emit(f"define {linkage} {self._type_to_ir(func.return_type)} @{name}({', '.join(params)}) {{")
        self._temp_idx = 0
        returns = self._emit_block(func.block)
        if not returns:
            self._emit("\tret void")
        self._emit("}")

    # Returns True if the block has a return statement
    def _emit_block(self, block: list[_Statement]) -> bool:
        for stmt in block:
            if isinstance(stmt, ReturnStmt):
                if stmt.expr is not None:
                    value = self._emit_expr(stmt.expr)
                    self._emit(f"\tret {self._type_to_ir(stmt.expr.type)} {value}")
                else:
                    self._emit("\tret void")
                return True

            # TODO: mem2reg won't be able to optimize this if allocas are not at the start of the function!
            # Should that be done during semantic analysis or during codegen before emitting statements?
            elif isinstance(stmt, VarStmt):
                if stmt.expr is None:
                    fatal_error("handle uninitialized variables, maybe?")
                else:
                    value = self._emit_expr(stmt.expr)
                    value_type = self._type_to_ir(stmt.expr.type)
                    self._emit(f"\t%{stmt.local} = alloca {value_type} ; bad!")
                    self._emit(f"\tstore {value_type} {value}, {value_type} %{stmt.local}")

            elif isinstance(stmt, ExprStmt):
                self._emit_expr(stmt.expr)

            elif isinstance(stmt, AssignStmt):
                if isinstance(stmt.assignee, _SymbolRefExpr):
                    value = self._emit_expr(stmt.value)

                    assignee_symbol = stmt.assignee.symbol
                    if isinstance(assignee_symbol, LocalSymbol):
                        value_type = self._type_to_ir(stmt.value.type)
                        self._emit(f"\tstore {value_type} {value}, {value_type} %{assignee_symbol.name}")
                    elif isinstance(assignee_symbol, FieldSymbol):
                        if not isinstance(stmt.assignee, MemberExpr):
                            fatal_error("FieldSymbol assignee must be a MemberExpr")

                        instance = self._emit_expr(stmt.assignee.target)
                        field_name = assignee_symbol.name

                        match assignee_symbol.type:
                            case BoolType(): fn = "zre_field_set_bool"
                            case IntType(): fn = "zre_field_set_int"
                            case ObjectType(_): fn = "zre_field_set_obj"
                            case _: fatal_error(f"Unsupported property type: {assignee_symbol.type}")

                        self._emit(f"\tcall void @{fn}(ptr {instance}, ptr {self._str_sym(field_name)}, {self._type_to_ir(stmt.value.type)} {value})")
                else:
                    fatal_error("Not an assignable expression")

            elif isinstance(stmt, IfStmt):
                if_idx = self._if_idx
                self._if_idx += 1

                end_label = f"if.{if_idx}.end"
                true_label = f"if.{if_idx}.true"
                if stmt.else_block is None:
                    false_label = end_label
                else:
                    false_label = f"if.{if_idx}.false"

                self._emit(f"\tbr i1 {self._emit_expr(stmt.condition)}, label %{true_label}, label %{false_label}")

                self._emit(f"{true_label}:")
                block_returns = self._emit_block(stmt.block)
                if not block_returns:
                    self._emit(f"\tbr label %{end_label}")

                if stmt.else_block is not None:
                    self._emit(f"{false_label}:")
                    else_returns = self._emit_block(stmt.else_block)
                    if not else_returns:
                        self._emit(f"\tbr label %{end_label}")

                self._emit(f"{end_label}:")
            else:
                print(f"Statement '{stmt}' is unknown")
        return False

    def _emit_expr(self, expr: _Expression, local: Optional[str] = None) -> str:
        def temp_local() -> str:
            if local is not None:
                return f"%{local}"
            sym = f"%.tmp.{self._temp_idx}"
            self._temp_idx += 1
            return sym

        if isinstance(expr, BoolExpr):
            return f"{1 if expr.value else 0}"

        elif isinstance(expr, IntExpr):
            return f"{expr.value}"

        elif isinstance(expr, StringExpr):
            temp = temp_local()
            self._emit(f"\t{temp} = call ptr @zre_string_literal(ptr {self._str_sym(expr.value)})")
            return temp

        elif isinstance(expr, SymbolExpr):
            symbol = expr.symbol
            if isinstance(symbol, ParameterSymbol):
                return f"%{symbol.name}"
            if isinstance(symbol, LocalSymbol):
                temp = temp_local()
                self._emit(f"\t{temp} = load {self._type_to_ir(symbol.type)}, {self._type_to_ir(symbol.type)} %{symbol.name}")
                return temp
            else:
                fatal_error(f"Unknown symbol type: {type(symbol)}")

        elif isinstance(expr, MemberExpr):
            # Assuming FieldSymbol
            instance = self._emit_expr(expr.target)
            field_name = expr.member
            temp = temp_local()

            match expr.type:
                case BoolType(): fn = "zre_field_get_bool"
                case IntType(): fn = "zre_field_get_int"
                case ObjectType(_): fn = "zre_field_get_obj"
                case _: fatal_error(f"Unsupported property type: {expr.type}")

            self._emit(f"\t{temp} = call {self._type_to_ir(expr.type)} @{fn}(ptr {instance}, ptr {self._str_sym(field_name)})")
            return temp

        elif isinstance(expr, CallExpr):
            call = expr
            args = [f"{self._type_to_ir(arg.type)} {self._emit_expr(arg)}" for arg in call.args]

            if isinstance(call.callee, SymbolExpr):
                function = call.callee.type
                if not isinstance(function, FunctionType):
                    fatal_error(f"Expression '{function}' is not a function")

                call = f"call {self._type_to_ir(function.return_type)} @_zr_{call.callee.name}({', '.join(args)})"
            elif isinstance(call.callee, MemberExpr):
                function = call.callee.type
                if not isinstance(function, FunctionType):
                    fatal_error(f"Expression '{function}' is not a function")

                fn_temp = temp_local()

                if isinstance(call.callee.target, SymbolExpr) and isinstance(call.callee.target.symbol, ParameterSymbol) and call.callee.target.symbol.name == "super":
                    # Such an ugly ugly hack to call the superclass method
                    if self._current_class is None:
                        fatal_error("No class or superclass")

                    super_class = self._current_class.super or "Object"
                    self._emit(f"\t{fn_temp} = call ptr @zre_method_super(ptr @{super_class}, ptr {self._str_sym(call.callee.member)}) ; {call.callee.member}")
                    args.insert(0, "ptr %self")
                elif isinstance(call.callee.target, SymbolExpr) and isinstance(call.callee.target.symbol, Class):
                    pass
                else:
                    callee = self._emit_expr(call.callee.target)
                    self._emit(f"\t{fn_temp} = call ptr @zre_method_virtual(ptr {callee}, ptr {self._str_sym(call.callee.member)}) ; {call.callee.member}")
                    args.insert(0, f"ptr {callee}")

                call = f"call {self._type_to_ir(function.return_type)} {fn_temp}({", ".join(args)})"
            else:
                fatal_error(f"Statement '{call.callee}' is not callable")

            if function.return_type == VoidType():
                self._emit(f"\t{call}")
                return ""
            else:
                temp = temp_local()
                self._emit(f"\t{temp} = {call}")
                return temp

        elif isinstance(expr, BinaryExpr):
            if expr.op == BinaryOperation.AND or expr.op == BinaryOperation.OR:
                fatal_error("Logical operators AND and OR are not implemented")

            lhs = self._emit_expr(expr.lhs)
            rhs = self._emit_expr(expr.rhs)

            ops: dict[BinaryOperation, str] = {
                BinaryOperation.ADD: "add",
                BinaryOperation.SUB: "sub",
                BinaryOperation.MUL: "mul",
                BinaryOperation.DIV: "sdiv",
                BinaryOperation.MOD: "srem",
                BinaryOperation.EQ: "icmp eq",
                BinaryOperation.NEQ: "icmp ne",
                BinaryOperation.GT: "icmp sgt",
                BinaryOperation.GTE: "icmp sge",
                BinaryOperation.LT: "icmp slt",
                BinaryOperation.LTE: "icmp sle",
            }
            temp = temp_local()
            self._emit(f"\t{temp} = {ops[expr.op]} {self._type_to_ir(expr.lhs.type)} {lhs}, {rhs}")
            return temp

        elif isinstance(expr, AllocExpr):
            temp = temp_local()
            self._emit(f"\t{temp} = call ptr @zre_alloc(ptr @{expr.cls_name})")
            return temp

        print(f"Expression '{expr}' is unknown")
        return "ERROR"

    def _type_to_ir(self, type: Type) -> str:
        if isinstance(type, VoidType):
            return "void"
        elif isinstance(type, BoolType):
            return "i1"
        elif isinstance(type, IntType):
            return "i64"
        elif isinstance(type, ObjectType):
            return "ptr"
        elif isinstance(type, FunctionType):
            return "ptr"

        fatal_error(f"Unknown type: {type}")
