import sys
from typing import Optional, NoReturn

from compiler.IR import IRFunction, IRInstruction, IRReturn, IROperand, IRReg, IRAlloc, IRVirtualCall, _IRCall, \
    IRFuncCall, IRStore, IRStorage, IRLoad, IRClass, IRMethod, IRSuperCall, IRStaticCall, IRSelf, IRLoadField, \
    IRStoreField, IRBinaryOp, IRBranch, IRRetain, IRRelease, IRStringLiteral, IRLoop, IRBreak, IRContinue, IRCheckDowncast, \
    IRNull
from compiler.symbols import FieldSymbol, Class, MethodSymbol, LocalSymbol, ParameterSymbol
from compiler.types import VoidType, BoolType, IntType, ObjectType, Type
from lang_ast import BinaryOperation


def fatal_error(msg: str) -> NoReturn:
    sys.exit(f"internal error: {msg}\nThis is a bug in the compiler, semantic analysis should've caught this!")


class LLVMIRGenerator:
    def __init__(self, funcs: list[IRFunction], classes: list[IRClass]):
        self.funcs = funcs
        self.classes = classes
        self._lines: list[str] = []
        self._strings: list[str] = []
        self._temp_idx: int = 0
        self._if_idx: int = -1
        self._loop_idx: int = -1
        self._loop_idx_current: int = -1

        self._declarations = [
            "declare ptr @zre_alloc(ptr)",
            "declare void @zre_retain(ptr)",
            "declare void @zre_release(ptr)",
            "declare void @zre_check_downcast(ptr, ptr)",
            "declare i1 @zre_field_get_bool(ptr, ptr)",
            "declare i64 @zre_field_get_int(ptr, ptr)",
            "declare ptr @zre_field_get_obj(ptr, ptr)",
            "declare void @zre_field_set_bool(ptr, ptr, i1)",
            "declare void @zre_field_set_int(ptr, ptr, i64)",
            "declare void @zre_field_set_obj(ptr, ptr, ptr)",
            "declare ptr @zre_method_super(ptr, ptr)",
            "declare ptr @zre_method_virtual(ptr, ptr)",
            "declare ptr @zre_string_literal(ptr)",
            # TODO: Better way to handle built-in types?
            "declare void @_zr_print(ptr)",
            "@Object = external constant ptr",
            "@String = external constant ptr",
            "@Array = external constant ptr",
            "@File = external constant ptr",
            "@User = external constant ptr",
        ]

    def generate(self) -> str:
        self._emit("; Generated by zrlang")

        for ir_func in self.funcs:
            self._emit_function(ir_func)

        for ir_cls in self.classes:
            self._emit_class(ir_cls)

        self._emit("\n; String data")
        for idx, string in enumerate(self._strings):
            self._emit(f"@.str.{idx} = private unnamed_addr constant [{len(string) + 1} x i8] c\"{string}\\00\"")

        self._emit("\n; External declarations")
        for decl in self._declarations:
            self._emit(decl)
        self._emit("")

        return "\n".join(self._lines)

    def _str_sym(self, string: str) -> str:
        self._strings.append(string)
        return f"@.str.{len(self._strings) - 1}"

    def _emit(self, line: str | list[str]):
        self._lines.append(line)

    def _emit_function(self, ir: IRFunction):
        self._emit(f"; ==== \"{ir.sym.name}\" Function ====")
        name = "main" if ir.sym.name == "main" else f"_zr_{ir.sym.name}"
        self._emit_function_impl(ir, name, linkage="")
        self._emit("")

    def _emit_class(self, ir: IRClass):
        cls = ir.sym
        self._emit(f"; ==== \"{cls.name}\" Class Definition ====")

        field_symbols = [m for m in cls.members.values() if isinstance(m, FieldSymbol)]
        if field_symbols:
            self._emit(f"@{cls.name}.fields = constant [{len(field_symbols)} x {{ ptr, i64 }}] [")
            def is_object(field):
                return isinstance(field.type, ObjectType)
            self._emit(",\n".join(f"\t{{ ptr, i64 }} {{ ptr {self._str_sym(field.name)}, i64 {0 if is_object(field) else 1} }}"
                                  for field in field_symbols))
            self._emit("]")

        instance_methods: list[IRMethod] = [m for m in ir.methods if not m.sym.is_static]
        static_methods: list[IRMethod] = [m for m in ir.methods if m.sym.is_static]

        if instance_methods:
            self._emit(f"@{cls.name}.instanceMethods = constant [{len(instance_methods)} x {{ ptr, ptr }}] [")
            self._emit(",\n".join(f"\t{{ ptr, ptr }} {{ ptr {self._str_sym(method.sym.name)}, ptr @{cls.name}.{method.sym.name} }}"
                                  for method in instance_methods))
            self._emit("]")

        # -- Class table ---
        self._emit(f"@{cls.name} = constant [8 x i64] [")
        self._emit(f"\ti64 ptrtoint(ptr {self._str_sym(cls.name)} to i64),")
        self._emit(f"\ti64 ptrtoint(ptr @{cls.parent.name or 'Object'} to i64),")

        if field_symbols:
            self._emit(f"\ti64 {len(field_symbols)}, i64 ptrtoint (ptr @{cls.name}.fields to i64),")
        else:
            self._emit("\ti64 0, i64 0,")

        self._emit("\ti64 0, i64 0,")

        if instance_methods:
            self._emit(f"\ti64 {len(instance_methods)}, i64 ptrtoint (ptr @{cls.name}.instanceMethods to i64)")
        else:
            self._emit("\ti64 0, i64 0")
        self._emit("]")
        # ---

        if instance_methods:
            self._emit(f"\n; ==== \"{cls.name}\" Instance Methods ====")
            for method in instance_methods:
                self._emit_method(cls, method)
        self._current_class = None

        if static_methods:
            self._emit(f"\n; ==== \"{cls.name}\" Static Methods ====")
            for method in static_methods:
                self._emit_method(cls, method)

    def _emit_method(self, cls: Class, ir: IRMethod):
        self._emit_function_impl(ir,
                                 f"{cls.name}.{ir.sym.name}",
                                 linkage="" if ir.sym.is_static else "internal",
                                 add_self=not ir.sym.is_static)

    def _emit_function_impl(self, ir_func: IRFunction, name: str, linkage: str = "", add_self: bool = False):
        params = [f"{self._type_to_ir(param_sym.type)} %{param_sym.name}" for param_sym in ir_func.sym.params]
        if add_self:
            params.insert(0, "ptr %self")

        self._emit(f"define {linkage} {self._type_to_ir(ir_func.sym.return_type)} @{name}({', '.join(params)}) {{")

        for local in ir_func.locals:
            self._emit(f"\t%l.{local.name} = alloca {self._type_to_ir(local.type)}")

        for param in ir_func.sym.params:
            self._emit(f"\t%p.{param.name} = alloca {self._type_to_ir(param.type)}")
            self._emit(f"\tstore {self._type_to_ir(param.type)} %{param.name}, ptr %p.{param.name}")

        self._emit(";")
        self._temp_idx = 0
        self._emit_block(ir_func.body)
        self._emit("}")

    def _emit_block(self, block: list[IRInstruction]):
        for instr in block:
            if isinstance(instr, IRReturn):
                if instr.value is None:
                    self._emit("\tret void")
                else:
                    self._emit(f"\tret {self._operand(instr.value)}")

            elif isinstance(instr, IRBinaryOp):
                if instr.op == BinaryOperation.AND or instr.op == BinaryOperation.OR:
                    fatal_error("Logical operators AND and OR are not implemented")

                ops: dict[BinaryOperation, str] = {
                    BinaryOperation.ADD: "add",
                    BinaryOperation.SUB: "sub",
                    BinaryOperation.MUL: "mul",
                    BinaryOperation.DIV: "sdiv",
                    BinaryOperation.MOD: "srem",
                    BinaryOperation.EQ: "icmp eq",
                    BinaryOperation.NEQ: "icmp ne",
                    BinaryOperation.GT: "icmp sgt",
                    BinaryOperation.GTE: "icmp sge",
                    BinaryOperation.LT: "icmp slt",
                    BinaryOperation.LTE: "icmp sle",
                }
                self._emit(
                    f"\t{self._reg(instr.destination)} = {ops[instr.op]} {self._operand_type(instr.lhs)} "
                    f"{self._operand_value(instr.lhs)}, {self._operand_value(instr.rhs)}"
                )

            elif isinstance(instr, IRBranch):
                self._emit_branch(instr)

            elif isinstance(instr, IRLoop):
                self._emit_loop(instr)

            elif isinstance(instr, IRBreak):
                if self._loop_idx_current < 0:
                    fatal_error("'break' outside of a loop")
                self._emit(f"\tbr label %loop.end.{self._loop_idx_current}")

            elif isinstance(instr, IRContinue):
                if self._loop_idx_current < 0:
                    fatal_error("'continue' outside of a loop")
                self._emit(f"\tbr label %loop.start.{self._loop_idx_current}")

            elif isinstance(instr, IRStore):
                self._emit(f"\tstore {self._operand(instr.value)}, ptr {self._storage_reg(instr.destination)}")

            elif isinstance(instr, IRLoad):
                self._emit(
                    f"\t{self._reg(instr.destination)} = "
                    f"load {self._type_to_ir(instr.destination.type)}, ptr {self._storage_reg(instr.source)}"
                )

            elif isinstance(instr, IRStoreField):
                fn: str
                match instr.field.type:
                    case BoolType():
                        fn = "zre_field_set_bool"
                    case IntType():
                        fn = "zre_field_set_int"
                    case ObjectType(_):
                        fn = "zre_field_set_obj"
                    case _:
                        fatal_error(f"Unsupported property type: {instr.field.type}")

                self._emit(
                    f"\tcall void @{fn}"
                    f"(ptr {self._operand_value(instr.target)}, ptr {self._str_sym(instr.field.name)}, {self._operand(instr.value)})"
                    f" ; {instr.field.name}"
                )

            elif isinstance(instr, IRLoadField):
                fn: str
                match instr.field.type:
                    case BoolType():
                        fn = "zre_field_get_bool"
                    case IntType():
                        fn = "zre_field_get_int"
                    case ObjectType(_):
                        fn = "zre_field_get_obj"
                    case _:
                        fatal_error(f"Unsupported property type: {instr.field.type}")

                self._emit(
                    f"\t{self._reg(instr.destination)} = "
                    f"call {self._type_to_ir(instr.destination.type)} @{fn}"
                    f"(ptr {self._operand_value(instr.target)}, ptr {self._str_sym(instr.field.name)})"
                    f" ; {instr.field.name}"
                )

            elif isinstance(instr, _IRCall):
                self._emit_call(instr)

            elif isinstance(instr, IRRetain):
                self._emit(f"\tcall void @zre_retain(ptr {self._reg(instr.obj)})")

            elif isinstance(instr, IRRelease):
                self._emit(f"\tcall void @zre_release(ptr {self._reg(instr.obj)})")

            elif isinstance(instr, IRAlloc):
                self._emit(f"\t{self._reg(instr.destination)} = call ptr @zre_alloc(ptr @{instr.cls.name})")

            elif isinstance(instr, IRStringLiteral):
                self._emit(
                    f"\t{self._reg(instr.destination)} = "
                    f"call ptr @zre_string_literal(ptr {self._str_sym(instr.value)})"
                )

            elif isinstance(instr, IRCheckDowncast):
                self._emit(f"\tcall void @zre_check_downcast(ptr {self._reg(instr.obj)}, ptr @{instr.cls.name})")

    def _emit_call(self, call: _IRCall):
        args = [self._operand(arg) for arg in call.args]

        ir: str
        if isinstance(call, IRFuncCall):
            ir = f"{self._type_to_ir(call.func.return_type)} @_zr_{call.func.name}"

        elif isinstance(call, IRStaticCall):
            ir = f"{self._type_to_ir(call.method.return_type)} @{call.cls.name}.{call.method.name}"

        elif isinstance(call, IRVirtualCall):
            fn_ptr = self._temp_reg()
            self._emit(
                f"\t{fn_ptr} = call ptr @zre_method_virtual"
                f"(ptr {self._operand_value(call.target)}, ptr {self._str_sym(call.method.name)})"
                f" ; {call.method.name}"
            )
            ir = f"{self._type_to_ir(call.method.return_type)} {fn_ptr}"
            args.insert(0, self._operand(call.target))

        elif isinstance(call, IRSuperCall):
            fn_ptr = self._temp_reg()
            self._emit(
                f"\t{fn_ptr} = call ptr @zre_method_super"
                f"(ptr @{call.cls.name}, ptr {self._str_sym(call.method.name)})"
                f" ; {call.method.name}"
            )
            ir = f"{self._type_to_ir(call.method.return_type)} {fn_ptr}"
            args.insert(0, self._operand(IRSelf()))

        else:
            fatal_error(f"Unsupported IR call type: {type(call)}")

        if call.destination is not None:
            self._emit(f"\t{self._reg(call.destination)} = call {ir}({", ".join(args)})")
        else:
            self._emit(f"\tcall {ir}({", ".join(args)})")

    def _emit_loop(self, loop: IRLoop):
        parent_loop = self._loop_idx_current
        self._loop_idx += 1
        self._loop_idx_current = self._loop_idx

        start_label = f"loop.start.{self._loop_idx}"
        end_label = f"loop.end.{self._loop_idx}"

        self._emit(f"\tbr label %{start_label}")
        self._emit(f"{start_label}:")
        self._emit_block(loop.body)

        self._emit(f"\tbr label %{start_label}")
        self._emit(f"{end_label}:")

        self._loop_idx_current = parent_loop

    def _emit_branch(self, branch: IRBranch):
        self._if_idx += 1

        end_label = f"if.end.{self._if_idx}"
        true_label = f"if.true.{self._if_idx}"
        if branch.false_block:
            false_label = f"if.false.{self._if_idx}"
        else:
            false_label = end_label

        self._emit(f"\tbr {self._operand(branch.condition)}, label %{true_label}, label %{false_label}")

        self._emit(f"{true_label}:")
        self._emit_block(branch.true_block)
        self._emit(f"\tbr label %{end_label}")

        if branch.false_block:
            self._emit(f"{false_label}:")
            self._emit_block(branch.false_block)
            self._emit(f"\tbr label %{end_label}")

        self._emit(f"{end_label}:")

    def _temp_reg(self) -> str:
        self._temp_idx += 1
        return f"%tmp.{self._temp_idx}"

    def _storage_reg(self, storage: IRStorage) -> str:
        match storage:
            case LocalSymbol(name):
                return f"%l.{name}"
            case ParameterSymbol(name):
                return f"%p.{name}"
            case _:
                fatal_error(f"Unsupported storage type: {type(storage)}")

    def _type_to_ir(self, t: Type) -> str:
        if isinstance(t, VoidType):
            return "void"
        elif isinstance(t, BoolType):
            return "i1"
        elif isinstance(t, IntType):
            return "i64"
        elif isinstance(t, ObjectType):
            return "ptr"

        fatal_error(f"Unsupported type for LLVM codegen: {t}")

    def _reg(self, reg: IRReg) -> str:
        return f"%.{reg.idx}"

    def _operand(self, operand: IROperand) -> str:
        return f"{self._operand_type(operand)} {self._operand_value(operand)}"

    def _operand_type(self, operand: IROperand) -> str:
        match operand:
            case IRReg(idx) as r:
                return self._type_to_ir(r.type)
            case IRSelf():
                return "ptr"
            case IRNull():
                return "ptr"
            case bool(_):
                return "i1"
            case int(_):
                return "i64"
            case _:
                fatal_error(f"Unknown operand type: {type(operand)}")

    def _operand_value(self, operand: IROperand) -> str:
        match operand:
            case IRReg(idx):
                return f"%.{idx}"
            case IRSelf():
                return "%self"
            case IRNull():
                return "null"
            case bool(b):
                return f"{1 if b else 0}"
            case int(i):
                return f"{i}"
            case _:
                fatal_error(f"Unknown operand type: {type(operand)}")
