#include "compiler.h"

#include "context.h"

static void compileClass(FILE* f, ClassDeclaration* cls) {
    fprintf(f, "# ==== \"%s\" Class Definition ====\n", cls->name);

    fprintf(f, "data $%s_fields = {\n", cls->name);
    size_t fieldCount = 0;
    for (ClassMember* member = cls->members; member->type != 0; member++) {
        if (member->type != CLASS_MEMBER_FIELD) continue;
        ClassFieldDecl* field = &member->as.field;
        fprintf(f, "\tl %s, l 0,\n", stringSymbol(field->name));
        fieldCount++;
    }
    fprintf(f, "}\n");

    fprintf(f, "data $%s_instanceMethods = {\n", cls->name);
    size_t instanceMethodCount = 0;
    for (ClassMember* member = cls->members; member->type != 0; member++) {
        if (member->type != CLASS_MEMBER_METHOD) continue;
        MethodDecl* method = &member->as.method;
        fprintf(f, "\tl %s, l $%s_%s,\n", stringSymbol(method->name), cls->name, method->name);
        instanceMethodCount++;
    }
    fprintf(f, "}\n");

    fprintf(f, "export data $%s = {\n", cls->name);
    fprintf(f, "\tl %s,\n", stringSymbol(cls->name));
    if (cls->super == NULL)
        fprintf(f, "\tl 0,\n");
    else
        fprintf(f, "\tl %s,\n", cls->super);
    fprintf(f, "\tl %lu, l $%s_fields,\n", fieldCount, cls->name);
    fprintf(f, "\tl 0, l 0,\n");
    fprintf(f, "\tl %lu, l $%s_instanceMethods,\n", instanceMethodCount, cls->name);
    fprintf(f, "}\n");

    fprintf(f, "\n");
}

void compile(const char* src, ClassDeclaration* classDecls) {
    FILE* f = fopen("ir.ssa", "w");

    fprintf(f, "# ==== Generated by zrc ==== \n\n");

    for (ClassDeclaration* cls = classDecls; cls->name != NULL; cls++) {
        compileClass(f, cls);
    }

    UnitContext* ctx = &UnitContext_current;
    fprintf(f, "# ==== String Data ==== \n");
    fprintf(f, "data $strings = { b \"");
    for (size_t i = 0; i < arrlen(ctx->strings); i++) {
        fprintf(f, "%s\\0", ctx->strings[i]);
    }
    fprintf(f, "\" }\n");

    fclose(f);
}